version: '3.1'
services:
  backend:
    image: traefik/whoami
  
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /keycloak/demo-realm.json
    ports:
      - 8180:8080
    volumes:
    - ./keycloak:/keycloak
