name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install requirements
      run: sudo apt-get install -y musl-tools
    - uses: actions/checkout@v2
    - name: Install rust target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-musl
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with: 
        command: fmt
        args: -- --check
    - name: Check clippy
      uses: actions-rs/cargo@v1
      with: 
        command: clippy
        args: -- -Dwarnings
    - name: Build musl
      uses: actions-rs/cargo@v1
      with: 
        command: build
        args: --release --target x86_64-unknown-linux-musl
