name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check clippy
      run: cargo clippy -- -Dwarnings
    - name: Build musl
      uses: docker://ekidd/rust-musl-builder:stable
      with:
        args: cargo build --release
    - name: Check outcome
      run: ls -R
