name: Create Release
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install requirements
      run: sudo apt-get install -y musl-tools
    - uses: actions/checkout@v2
    - name: Install rust target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
        target: x86_64-unknown-linux-musl
    - name: Build musl
      uses: actions-rs/cargo@v1
      with: 
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - name: Strip binary
      run: strip target/x86_64-unknown-linux-musl/release/oauth-proxy-rs
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: untoldwind/jenkins-kube:${{ env.TAG }}
